# Generated by Django 5.2.16 on 2026-09-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='training_place',
            field=models.CharField(help_text='Physical location or online training platform', max_length=255, null=True),
        ),
    ]
