# Generated by Django 5.2.16 on 2026-09-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0002_trainingrequest_end_date_trainingrequest_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
