# Generated by Django 5.2.16 on 2026-09-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0003_trainingrequest_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('ATTACHMENT_WAIT', 'waiting attachment'), ('SUBMITTED', 'Submitted'), ('PENDING_DEPT', 'Pending Department Approval'), ('PENDING_BUDGET', 'Pending Budget Approval'), ('DEPARTMENT_APPROVED', 'Department Approved'), ('BUDGET_APPROVED', 'Budget Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='ATTACHMENT_WAIT', max_length=30),
        ),
    ]
