# Generated by Django 5.2.16 on 2026-09-04 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0004_alter_trainingrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_type',
            field=models.CharField(choices=[('TRAINING_DOCUMENT', 'Training document'), ('QUOTATION', 'Quotation'), ('OTHER', 'Other supporting document')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
