# Generated by Django 5.2.17 on 2026-09-14 10:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0007_trainingrequestparticipantresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrequest',
            name='create_at',
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Target recipient / HOD reviewing this request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_training_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_DEPT', 'Pending Department Approval'), ('DEPARTMENT_APPROVED', 'Department Approved'), ('HRO_REVIEW', 'Pending HRO Nomination'), ('PENDING_HR_DIRECTOR', 'Pending HR Director Approval'), ('PENDING_BUDGET', 'Pending Budget Approval'), ('BUDGET_APPROVED', 'Budget Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='training_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainingRequestItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('desired_outcome', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOMINATED', 'Nominated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('planned_year', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_month', models.PositiveSmallIntegerField(blank=True, help_text='Month 1 to 12', null=True)),
                ('training_place', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tna.trainingrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
