# Generated by Django 5.2.17 on 2026-09-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0008_remove_trainingrequest_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='anonymized_reference',
            field=models.CharField(blank=True, help_text='Unbiased reference code e.g. ENG-0042', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='budget_line_item',
            field=models.CharField(blank=True, help_text='Validated budget line item code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='calendar_invites_sent',
            field=models.BooleanField(default=False, help_text='Calendar invitations coordinated and sent'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='eligibility_verified',
            field=models.BooleanField(default=False, help_text='HRO verified employee eligibility records'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Anonymized for unbiased strategic evaluation'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='logistics_dates',
            field=models.CharField(blank=True, help_text='Execution dates locked by HRO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='logistics_vendor',
            field=models.CharField(blank=True, help_text='Selected training vendor / institute', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='logistics_venue',
            field=models.CharField(blank=True, help_text='Booked location / training platform', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOD_APPROVED', 'HOD Approved'), ('HRO_PROCESSED', 'HRO Processed'), ('STRATEGIC_APPROVED', 'Strategic Approved'), ('FULFILLMENT_ACTIVE', 'Fulfillment Active'), ('COMPLETED', 'Completed'), ('PENDING_DEPT', 'Pending Department Approval'), ('DEPARTMENT_APPROVED', 'Department Approved'), ('HRO_REVIEW', 'Pending HRO Nomination'), ('PENDING_HR_DIRECTOR', 'Pending HR Director Approval'), ('PENDING_BUDGET', 'Pending Budget Approval'), ('BUDGET_APPROVED', 'Budget Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='SUBMITTED', max_length=30),
        ),
    ]
