# Generated by Django 5.2.17 on 2026-09-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0009_trainingrequest_anonymized_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tna.trainingrequestitem'),
        ),
    ]
