# Generated by Django 5.2.17 on 2026-09-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('HR_MANAGER', 'HR / Training Manager'), ('HRO', 'Human Resource Officer'), ('DEPT_HEAD', 'Department Head / Supervisor'), ('FINANCE', 'Finance / Budget Approver'), ('EMPLOYEE', 'Employee'), ('TRAINER', 'Trainer'), ('DIRECTOR', 'Manager Director')], max_length=50, unique=True),
        ),
    ]
