# Generated by Django 5.2.16 on 2026-09-04 12:31

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_airequest_airesponse'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
