# Generated by Django 5.2.16 on 2026-09-04 16:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_knowledgechunk_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
